# Generated by Django 4.1.2 on 2022-12-30 19:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cart',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
