# Generated by Django 4.1.2 on 2023-02-21 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_active_user_admin_user_email_user_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='confirmed_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 2, 21, 23, 28, 31, 8833, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
