# Generated by Django 4.1.2 on 2022-11-22 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
    ]
